{% set version = "0.11.0" %}
{% set sha256 = "2eea0cc95b312e136e6e5abc64e2e62baaeca493cd32f553c2205f79e01c0423" %}

package:
  name: jupyterlab_launcher
  version: {{ version }}

source:
  fn: jupyterlab_launcher-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterlab_launcher/jupyterlab_launcher-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    number: 0
    script: python -m pip install --no-deps .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - notebook

test:
  imports:
    - jupyterlab_launcher

about:
  home: http://github.com/jupyterlab/jupyterlab_launcher
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A Launcher for JupyterLab based applications.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
