travis:
  secure:
    BINSTAR_TOKEN: m6stOT3A6kv8ToPu+xtykf8LqhjGFokWPcQ9oednHen9tj4km9QFpnDD/Q6ERQV76UtkDS4BBTOre4MvFnI4U6dK80P9zRQUPijWRsXLjhpp2b90MRvAvQh86tg//elAHt4sZZZ/IuXIgNN/p2P35fjB+4JTHLWa7wmF+peyp13tKqI/tq4l73jcoaL4ins3/hhLFl0qJ/J3BAkcForLEdZ7limbOh9MdSThpMSrKPOm9ebWJMCc2CSIMiDwH77EpSFW+N/XXAxvHMv4lEb1EYtnIM3AGgJPYCjNiGh5iZEgVShFoavPQUZcl/f+OVWUG6tfHdkKY96YaPBn8Qz/gJYB77sXwMLaWjy1a3n2CW5VrVDHwaI1ie9ghwbOlbv+rDQ1TcmVXPr/tdpKbiD7C41t/nKuRcX7UCtlh3+ctkcGslQQCq9oC/+KNekspUnLL6E6PI4DaWrzJnOAi22yObnMbUws354EWKHE6iFKhXYcb2NUI/0rZww+98xObP6NW/zE1Y3C0IF3y7D/yNMHbZuA95c8oauk9dzsU0z0H96+do7NpiSvU+jWUYFpiWkZrH4JqEhvsg7GmqkIOjwhmp6026NYLBtxJgOaKCISKv6pdMYbtP/1JCiWhChQ1cX8wtPtGqMVhNXH7TF25V7XAL1AkkaJqOpJ8EeJa6PvCgM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
